package web;

public enum CommunicationSignal {
	START, GAME_ALREADY_FULL, PREMATURE_END_ERROR, GAME_OVER,
	NOT_YOUR_TURN, YOUR_TURN,
	YOU_LOSE, YOU_WIN, TIE,
	ALREADY_FILLED_UP_SQUARE, MOVE_OUT_OF_RANGE,
	OPPONENTS_MOVE,
	GRID_SIZE_TOO_SMALL, GRID_SIZE_TOO_BIG, STREAK_LENGTH_TOO_SMALL,
	STREAK_LENGTH_BIGGER_THAN_GRID,
	WRONG_GRID_SIZE, WRONG_STREAK_LENGTH
}
