package web;

public enum CommunicationSignal {
	// server signals
	GAME_ALREADY_FULL, NOT_YOUR_TURN,
	YOU_LOSE, YOU_WIN, TIE,
	ALREADY_FILLED_UP_SQUARE, MOVE_OUT_OF_RANGE,
	OPPONENTS_MOVE,
	GRID_SIZE_TOO_SMALL, GRID_SIZE_TOO_BIG, STREAK_LENGTH_TOO_SMALL,
	STREAK_LENGTH_BIGGER_THAN_GRID,
	WRONG_GRID_SIZE, WRONG_STREAK_LENGTH, 
	PREMATURE_END_ERROR, WRONG_MESSAGE,
	// client signals
	MY_MOVE,
	// shared signals
	START
}
