package game.communication.enums;

public enum CommunicationError {
	PREMATURE_END_ERROR, WRONG_MESSAGE_FORMAT, 
	INCONSISTENT_MESSAGE,
	//MESSAGE_NOT_APPLICABLE,
	GAME_ALREADY_OCCUPIED, GAME_ALREADY_EXIST,
	GAME_DOESNT_EXIST,
	// related to game metadata
	GRID_SIZE_TOO_SMALL, GRID_SIZE_TOO_BIG, STREAK_LENGTH_TOO_SMALL,
	STREAK_LENGTH_BIGGER_THAN_GRID, REQUIRED_FIELD_NULL_OR_EMPTY,
}
